### ISSUE TITLE
Configure django container to reload on file change

### ISSUE THREAD

**Issue by denisemauldin** [devroastproject/devroastproject#29]
The django container currently runs this command from the Dockerfile:
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "devroast.wsgi"]

This doesn't reload when the files inside the container change, so therefore the container has to be restarted.

https://docs.docker.com/compose/django/

This recommends adding a volume mount for the django code and overriding the command to use runserver instead of gunicorn.

**Comment by crg253** [comment]
I'll work on this issue.
